development:
  secret_key_base: 4f61156c0733a7c8127cefe77b05dbe14de924f243a67f6da63ffdeb415fc4e4ee36acadb352558317f02a329e1f52ddd01a1957dd0f3e033a32ef62f64f5cdb
  stackapps_client_id: <%= ENV["STACKAPPS_CLIENT_ID"] %>
  stackapps_client_secret: <%= ENV["STACKAPPS_CLIENT_SECRET"] %>
  stackapps_api_key: <%= ENV["STACKAPPS_API_KEY"] %>
  exception_notification_recipient: joe.bloggs@gmail.com
  google_analytics_tracker_code: UA-123

test:
  secret_key_base: 517f7fceae7dcc612d2def6bb7486b038ff29d0ba0ac32a0f68ce549085084709a33787c5c8283c7fc6063b5d7f4d86a69faf99e8336817956f5329a613ef860
  stackapps_client_id: <%= ENV["STACKAPPS_CLIENT_ID"] %>
  stackapps_client_secret: <%= ENV["STACKAPPS_CLIENT_SECRET"] %>
  stackapps_api_key: <%= ENV["STACKAPPS_API_KEY"] %>
  exception_notification_recipient: joe.bloggs@gmail.com
  google_analytics_tracker_code: UA-123

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stackapps_client_id: <%= ENV["STACKAPPS_CLIENT_ID"] %>
  stackapps_client_secret: <%= ENV["STACKAPPS_CLIENT_SECRET"] %>
  stackapps_api_key: <%= ENV["STACKAPPS_API_KEY"] %>
  exception_notification_recipient: <%= ENV["EXCEPTION_NOTIFICATION_RECIPIENT"] %>
  google_analytics_tracker_code: <%= ENV["GOOGLE_ANALYTICS_TRACKER_CODE"] %>
